
Collecting tasks from: tasks.py
======================= Running: [96mrobot_spare_bin_python[0m ========================
[96mrobot_spare_bin_python[0m status: [91mFAIL
[0m[91m
Locator.inner_html: Timeout 30000ms exceeded.
Call log:
  - waiting for locator("sales-results")

[0m=============== Full Traceback (running [96mrobot_spare_bin_python[0m) ================
[91mTraceback (most recent call last):
  File "/Users/Shared/sema4ai/ht/e4f6f17_c5e81ff_1c0bc041/lib/python3.12/site-packages/robocorp/tasks/_commands.py", line 453, in run
    result = task.run(**kwargs)
             ^^^^^^^^^^^^^^^^^^
  File "/Users/Shared/sema4ai/ht/e4f6f17_c5e81ff_1c0bc041/lib/python3.12/site-packages/robocorp/tasks/_task.py", line 57, in run
    return self.method(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aditiphadnis/Documents/Github Projects/marias-robot/tasks.py", line 20, in robot_spare_bin_python
    export_to_pdf()
  File "/Users/aditiphadnis/Documents/Github Projects/marias-robot/tasks.py", line 75, in export_to_pdf
    sales_results_html = page.locator("sales-results").inner_html()
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Shared/sema4ai/ht/e4f6f17_c5e81ff_1c0bc041/lib/python3.12/site-packages/playwright/sync_api/_generated.py", line 16838, in inner_html
    self._sync(self._impl_obj.inner_html(timeout=timeout))
  File "/Users/Shared/sema4ai/ht/e4f6f17_c5e81ff_1c0bc041/lib/python3.12/site-packages/playwright/_impl/_sync_base.py", line 115, in _sync
    return task.result()
           ^^^^^^^^^^^^^
  File "/Users/Shared/sema4ai/ht/e4f6f17_c5e81ff_1c0bc041/lib/python3.12/site-packages/playwright/_impl/_locator.py", line 436, in inner_html
    return await self._frame.inner_html(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Shared/sema4ai/ht/e4f6f17_c5e81ff_1c0bc041/lib/python3.12/site-packages/playwright/_impl/_frame.py", line 623, in inner_html
    return await self._channel.send("innerHTML", locals_to_params(locals()))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Shared/sema4ai/ht/e4f6f17_c5e81ff_1c0bc041/lib/python3.12/site-packages/playwright/_impl/_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Shared/sema4ai/ht/e4f6f17_c5e81ff_1c0bc041/lib/python3.12/site-packages/playwright/_impl/_connection.py", line 528, in wrap_api_call
    raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
playwright._impl._errors.TimeoutError: Locator.inner_html: Timeout 30000ms exceeded.
Call log:
  - waiting for locator("sales-results")


[0m================================================================================
Robocorp Log (html): /Users/aditiphadnis/Documents/Github Projects/marias-robot/output/log.html
